### ISSUE TITLE
tidy debugging info

### ISSUE THREAD

**Issue by GarryMorrison** [GarryMorrison/Feynman-knowledge-engine#15]
currently debugging info is verbose, and everywhere! We need a way to have a tidy output.
But we occasionally would still want debugging info, so perhaps:
$ ./the_semantic_db_console.py --debugging

**Comment by allthingsgo** [comment]
on my wish list as well...

**Comment by GarryMorrison** [comment]
I have the basics in place.
eg:
$ ./the_semantic_db_console.py  --debug

and:
sa: debug on
sa: debug off

Now just need to change all my print statements to logger.debug("message").
Not hard, just boring.
Also, all at the DEBUG level, or are some at INFO level?
I'll have to read the code to decide.

Also need to decide which ones we really want to keep. There is a lot of junk that is not all that useful for debugging.

Just discovered, it handles things differently from print()
eg: this is valid: print("op:",op)
this is not: logger.debug("op:",op)
this is valid: logger.debug("op: " + op)
ie, print() auto-casts to string, logging function does not.

**Comment by GarryMorrison** [comment]
slowly making progress on this one

We now also have:
$ ./the_semantic_db_console.py --info

and:
sa: info on
sa: info off

**Comment by GarryMorrison** [comment]
no longer an issue. By default info and debug are now off, and the console output is nice and clean.
Though we do have a few stray debug/info statements that are passed being useful and should be deleted.
