### ISSUE TITLE
tweak loading of files?

### ISSUE THREAD

**Issue by GarryMorrison** [GarryMorrison/Feynman-knowledge-engine#17]
currently we have:
load_sw(C,some-sw-file)
do stuff ...
save_sw(C,some-sw-file)

maybe load and save should be in the context_list class instead?
eg:
C.load(some-sw-file)
do stuff ...
C.save(some-sw-file)

Currently load_sw() and save_sw() are in the processor file, not the code classes file.

**Comment by allthingsgo** [comment]
does file's encoding handling come into this consideration?

**Comment by GarryMorrison** [comment]
pretty sure I will implement this change.
Also, something like:
C.append_save(some-file.sw)
We can then use that to save state to file as we go, instead of keeping it in memory for the entire duration of the script.

**Comment by GarryMorrison** [comment]
```
finally implemented:
context.save(filename)
context.load(filename)
context.append_save(filename)
context.multi_save(filename)
Did some rough testing, and they seem to be correct.
```

Took a little more work than I thought it would. 
Also, I didn't remove the old methods from the processor file, but they are now deprecated, and will be removed at some point.
