### ISSUE TITLE
failed to load bug

### ISSUE THREAD

**Issue by GarryMorrison** [GarryMorrison/Feynman-knowledge-engine#27]
Just noticed this on creating the sw index file:
http://semantic-db.org/sw-examples/

failed to load: sw-examples/africa.sw
failed to load: sw-examples/fragment-documents-2.sw
failed to load: sw-examples/fragment-documents.sw
failed to load: sw-examples/sw-files-to-frequency-lists.sw

I don't recall seeing this error before. Must be some bug in the new parser code, I presume.

Track it down and fix!

**Comment by allthingsgo** [comment]
Did you catch the bug?  new parser doesn't like  " ASCII text, with CRLF line terminators" ?
