### ISSUE TITLE
decide license for my code

### ISSUE THREAD

**Issue by GarryMorrison** [GarryMorrison/Feynman-knowledge-engine#4]
I need to decide on a license for my code. Probably GPLv3, but haven't yet decided.

**Comment by allthingsgo** [comment]
Text-in-time by this publisher uses Adobe Digital Edition for viewing any copy of the original content from all sorts of digital sources with quite 'restrictive' copyright/access permission, which is good for the original content producer and reseller, imho.  Also I find auto-rendering from your html page on 'supervised learning' looks 'shifted' ... I'll check back here when you decide on a license.  And let me know if I need to 'withdraw/replace' any of my test run to incorporate your new license etc. thanks - susan

![adobedigital p259](https://cloud.githubusercontent.com/assets/5673681/8972866/2e0be0ba-362c-11e5-9a5f-6763b4624f3e.png)

**Comment by GarryMorrison** [comment]
now officially GPLv3
